### ISSUE TITLE
Trying to control RobotIQ gripper from remote control on UR10e

### ISSUE THREAD

**Issue by afonsocastro** [afonsocastro/larcc_interface#1]
See [this issue](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/240) and try [this](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/240#issuecomment-774981870) solution.

**Comment by afonsocastro** [comment]
By following the last advice:

1. python -m pip install pyserial


1. Clone the repo to my catkin_ws/src:

```
cd catkin_ws/src
git clone https://github.com/DavidYaonanZhu/robotiq.git
```

2. Change the shebang line: "python" -> "python3" of file _robotiq_modbus_rtu/src/robotiq_modbus_rtu/comModbusRtu.py_

3. Install soem:
```
sudo apt install ros-noetic-soem
```

4. Delete all the packages of 3 fingers grippers (delete folders with _3f_ on name)

5. Build catkin:
```
cd ~catkin_ws/
catkin_make
```

**Comment by afonsocastro** [comment]
when I try to run 
```
rosrun robotiq_2f_gripper_control Robotiq2FGripperRtuNode.py /tmp/ttyUR
```
I get the error
```
Traceback (most recent call last):
  File "/home/afonsocastro/catkin_ws/src/robotiq/robotiq_2f_gripper_control/nodes/Robotiq2FGripperRtuNode.py", line 89, in <module>
    mainLoop(sys.argv[1])
  File "/home/afonsocastro/catkin_ws/src/robotiq/robotiq_2f_gripper_control/nodes/Robotiq2FGripperRtuNode.py", line 60, in mainLoop
    gripper.client.connectToDevice(device)
  File "/home/afonsocastro/catkin_ws/src/robotiq/robotiq_modbus_rtu/src/robotiq_modbus_rtu/comModbusRtu.py", line 59, in connectToDevice
    if not self.client.connect():
  File "/home/afonsocastro/.local/lib/python3.8/site-packages/pymodbus/client/sync.py", line 489, in connect
    self.socket.interCharTimeout = self.inter_char_timeout
AttributeError: 'NoneType' object has no attribute 'interCharTimeout'

```

**Comment by afonsocastro** [comment]
At this point, there are 4 paths to explore:

1. Try to continue following this tip, by installing the rs485 urcap (as suggested)
2. Ask Eurico for help, with a more personal advice
3. Ask Luís Rodrigues (GrowSkills) for any external program (or API) to control the gripper [DONE]
4. Try to use MoveIt, by augmenting the robot xacro to include the gripper model and controller

**Comment by afonsocastro** [comment]
After a small talk with Ruben Almeida from GrowSkills, I got to know that there is a windows software to remotely control the gripper.
This software requires the **gripper to be directly connected to the computer**, using an **adapter DIN 8 pin to USB**.

![image](https://user-images.githubusercontent.com/47828797/154376625-44277866-0749-4439-b719-6016fae2f8f4.png)

Software setup: https://assets.robotiq.com/website-assets/support_documents/document/RUI-2.4.6_20210412.zip?_ga=2.46399399.1691531527.1644949562-432766125.1556040441 

First of all, I do not have this cable yet, so I couldn't test it.
Secondly, this approach is not ideal for my purpose. For that reason, I will still try to establish the communication between the computer and the robot for gripper remote control.

**Comment by afonsocastro** [comment]
An alternative to [this last solution](https://github.com/afonsocastro/larcc_interface/issues/1#issuecomment-1042420791), presented by Ruben Almeida (GrowSkills), is to send a message, via TCP/IP communication to the robot, with the intended commands. 
The robot can only read files of type urscript, so we should write one file of that type and then send it as a message to the UR10e controller. 

There is a tutorial that show how this communication can be established:
[https://www.universal-robots.com/articles/ur/interface-communication/tcpip-socket-communication-via-urscript/](https://www.universal-robots.com/articles/ur/interface-communication/tcpip-socket-communication-via-urscript/)

I feel that this solution is the basic for the structure that I am looking for. This is the low level communication, and it can be built a software on top of it. 
I think that this is precisely what [robotiq](http://wiki.ros.org/robotiq) repository uses to communicate. But all of my problems are precisely by trying to use robotiq repo...

No sure what more to think about this, I will continue my research.

**Comment by afonsocastro** [comment]
Helpful hint: It is not possible to send gripper command functions through URScripts.
These type of commands are unknown to the UR controller. 
When we have a URcap installed, we can call the URcap functions to our TP programs.
Here is a more detailed description:

"  **Native UR command like moveL or servoJ can be sent directly to port 30002.  All functions implemented by a URCap like the Robotiq Gripper function are unknown even if the URCap is installed.  When a program is written on the teach pendant, all URCap function definitions are implemented in this program each time it is compiled and executed by the UR controller.  This means if you try to send the command line rq_move_and_wait(58) function to the controller by the port 30003, it will never work because it's unknown to the controller.
To achieve a gripper function, the definition of this function must also be sent.**  "

Further information, see this: [https://dof.robotiq.com/discussion/1649/control-gripper-via-ur-controller-client-interface](https://dof.robotiq.com/discussion/1649/control-gripper-via-ur-controller-client-interface)

**Comment by afonsocastro** [comment]
Currently, I am trying this [new solution](https://gist.github.com/felixvd/d538cad3150e9cac28dae0a3132701cf).

Based on the discussion posted [here](https://dof.robotiq.com/discussion/1962/programming-options-ur16e-2f-85#latest)

**Comment by afonsocastro** [comment]
Following my last comment, I sent an email to Felix von Drigalski and I got the answer:

"Yes, we did figure out a way (you just need to address the right port) and I just posted our source code in the thread.

It is the complete ROS1 setup we used in a robot competition, with two UR5e arms, Robotiq grippers, cameras, force control and simultaneous motion. Our journal paper about it should come out later this year. Please feel free to cite it if is useful: [https://github.com/o2ac/o2ac-ur](https://github.com/o2ac/o2ac-ur)"

It wasn't that much of a help, since I still cannot control the gripper.

**Comment by afonsocastro** [comment]
For future reference, in our last possible approach, it is possible to control the gripper through a direct connection to the computer, using a USB-RS485 cable adapter and following this old example: [https://blog.robotiq.com/controlling-the-robotiq-2f-gripper-with-modbus-commands-in-python](https://blog.robotiq.com/controlling-the-robotiq-2f-gripper-with-modbus-commands-in-python)

**Comment by afonsocastro** [comment]
Next step: try this.
[https://github.com/TechMagicKK/RobotiqHand](https://github.com/TechMagicKK/RobotiqHand)

**Comment by afonsocastro** [comment]
I have found the solution! :smiley: 

Following my last comment, I ended up by exploring the 5th option (by establishing a rs485 communication).
[https://dof.robotiq.com/discussion/1926/python-module-for-control-robotiq-2f-85-from-external-ubuntu-pc](https://dof.robotiq.com/discussion/1926/python-module-for-control-robotiq-2f-85-from-external-ubuntu-pc)
For the good use of this method, the RobotIQ URCap should be uninstalled (since this urcap also communicates with the gripper through rs485 protocol). 
There is no need to have the TeachPendant in Remote Mode nor running any program in Local Mode (it work both ways). 
This solution is doing exactly the same as if it was the RobotIQ URCap.

It's now time to add the necessary instructions to ReadMe.

**Comment by afonsocastro** [comment]
To help to create future commands (more than the ones already created) it will be useful to check all the rs485 commands described in [Instructions Manual](https://assets.robotiq.com/website-assets/support_documents/document/2F-85_2F-140_Instruction_Manual_CB-Series_PDF_20190122.pdf) from page 63 - 78.

Besides this, an [ASCII Chart]( https://www.commfront.com/pages/ascii-chart) could also be helpful.
